-- migrate:up
insert into comment (user_id, posting_id, comment) values (2, 47, '와 죽이네요');
insert into comment (user_id, posting_id, comment) values (9, 10, '이건 뭔가요?? 와 죽이네요');
insert into comment (user_id, posting_id, comment) values (10, 10, '안본 눈 삽니다');
insert into comment (user_id, posting_id, comment) values (8, 43, '와 이건 뭔가요? 정말 죽이네요');
insert into comment (user_id, posting_id, comment) values (9, 40, '와 이건 정말 뭔가요? 정말 죽이네요');
insert into comment (user_id, posting_id, comment) values (2, 17, '본 눈도 삽니다');
insert into comment (user_id, posting_id, comment) values (6, 9, '아이유 짱');
insert into comment (user_id, posting_id, comment) values (8, 5, '오빠 내가 잘못했어 돌아와줘');
insert into comment (user_id, posting_id, comment) values (11, 22, '오빠 내가 잘못했어 다시 돌아와줘');
insert into comment (user_id, posting_id, comment) values (11, 49, '오빠 내가 잘못했어 다시 돌아와줘 정말이야');
insert into comment (user_id, posting_id, comment) values (2, 40, '오빠 내가 잘못했어 다시 돌아와줘 미안해');
insert into comment (user_id, posting_id, comment) values (8, 35, '여보 사랑해');
insert into comment (user_id, posting_id, comment) values (1, 32, '여보 애기가 보고싶어해');
insert into comment (user_id, posting_id, comment) values (10, 48, '자기야 자? ');
insert into comment (user_id, posting_id, comment) values (1, 1, '자기야 자?');
insert into comment (user_id, posting_id, comment) values (7, 36, '자기야 자?');
insert into comment (user_id, posting_id, comment) values (6, 27, '오빠 내가 잘못했어 다시 돌아와줘');
insert into comment (user_id, posting_id, comment) values (2, 42, '식사는 하고 다니냐?');
insert into comment (user_id, posting_id, comment) values (6, 28, '오빠 내가 잘못했어 다시 돌아와줘');
insert into comment (user_id, posting_id, comment) values (9, 39, '사진이 참 좋네요 팔로우 하고 갑니다. 우리 소통해요');
insert into comment (user_id, posting_id, comment) values (1, 10, '사진이 참 좋네요 팔로우 하고 갑니다. 우리 소통해요');
insert into comment (user_id, posting_id, comment) values (1, 10, '사진이 참 좋네요 팔로우 하고 갑니다. 우리 소통해요');
insert into comment (user_id, posting_id, comment) values (8, 48, '사진이 참 좋네요 팔로우 하고 갑니다. 우리 소통해요 정말요');
insert into comment (user_id, posting_id, comment) values (5, 36, '사진이 참 좋네요 팔로우 하고 갑니다. 우리 소통해요 진짜요');
insert into comment (user_id, posting_id, comment) values (11, 44, '사진이 참 좋네요 팔로우 하고 갑니다. 우리 소통해요 완전요');
insert into comment (user_id, posting_id, comment) values (7, 29, '사진이 참 좋네요 팔로우 하고 갑니다. 우리 친하게 지내요');
insert into comment (user_id, posting_id, comment) values (4, 11, '사진이 참 좋네요 팔로우 하고 갑니다. 우리 친하게 지내요 정말요');
insert into comment (user_id, posting_id, comment) values (1, 3, '사진이 참 좋네요 팔로우 하고 갑니다. 우리 친하게 지내요 완전요');
insert into comment (user_id, posting_id, comment) values (11, 18, '샤오롱빠 정말 맛있네요');
insert into comment (user_id, posting_id, comment) values (9, 41, '샤오롱빠 정말 맛있네요 강추');
insert into comment (user_id, posting_id, comment) values (1, 2, '샤오롱빠 정말 맛있네요 완전');
insert into comment (user_id, posting_id, comment) values (11, 20, '커피가 식어간다');
insert into comment (user_id, posting_id, comment) values (7, 9, '커피가 식어간다 나는 고독하다');
insert into comment (user_id, posting_id, comment) values (7, 19, '커피가 식어간다. 배도 고프다');
insert into comment (user_id, posting_id, comment) values (7, 38, '망할 녀석들');
insert into comment (user_id, posting_id, comment) values (8, 30, '역시 광어회가 짱이야');
insert into comment (user_id, posting_id, comment) values (1, 10, '여기 빠져들것 같아요');
insert into comment (user_id, posting_id, comment) values (11, 33, '안전운전하세요');
insert into comment (user_id, posting_id, comment) values (11, 17, '안전운행하세요');
insert into comment (user_id, posting_id, comment) values (5, 3, '밥은 먹고 다니냐 ㅎㅎ');
insert into comment (user_id, posting_id, comment) values (9, 35, '밥은 먹고 다니냐 ㅎㅎㅎ ');
insert into comment (user_id, posting_id, comment) values (6, 5, '밥은 먹고 다니냐 ㅎㅎㅎㅎㅎ');
insert into comment (user_id, posting_id, comment) values (11, 24, '밥은 먹고 다니냐 ㅋㅋㅋㅋ');
insert into comment (user_id, posting_id, comment) values (7, 9, '밥은 먹고 다니냐 ㅎㅋ');
insert into comment (user_id, posting_id, comment) values (6, 5, '밥은 먹고 다니냐 ㅋ');
insert into comment (user_id, posting_id, comment) values (3, 44, '오호호');
insert into comment (user_id, posting_id, comment) values (7, 35, '오호호호');
insert into comment (user_id, posting_id, comment) values (10, 23, 'ㅋㅋㅋ');
insert into comment (user_id, posting_id, comment) values (4, 2, '러브다이브 흥해랏');
insert into comment (user_id, posting_id, comment) values (6, 44, '언제적 러브다이브냣');
insert into comment (user_id, posting_id, comment) values (4, 29, '못생긴게');
insert into comment (user_id, posting_id, comment) values (3, 37, '저스트코드 7기다');
insert into comment (user_id, posting_id, comment) values (4, 26, '저스트코드 6기다 고개숙여라');
insert into comment (user_id, posting_id, comment) values (10, 9, '저스트코드 5기다 안녕');
insert into comment (user_id, posting_id, comment) values (4, 15, '난 위코드다');
insert into comment (user_id, posting_id, comment) values (9, 13, '카카오톡에서 왔습니다.');
insert into comment (user_id, posting_id, comment) values (8, 12, '쿠팡에서 왔습니다.');
insert into comment (user_id, posting_id, comment) values (1, 6, '배민입니다.');
insert into comment (user_id, posting_id, comment) values (7, 49, '라인입니다.');
insert into comment (user_id, posting_id, comment) values (1, 8, 'HTML로 프로그래밍하는걸 좋아합니다.');
insert into comment (user_id, posting_id, comment) values (10, 33, '난 CSS가 좋아요');
insert into comment (user_id, posting_id, comment) values (8, 28, '역시 mySQL');
insert into comment (user_id, posting_id, comment) values (6, 4, '안녕하세요 ');
insert into comment (user_id, posting_id, comment) values (9, 17, '드디어 끝이 보인다');
insert into comment (user_id, posting_id, comment) values (10, 30, '아직 끝이 안보인다');
insert into comment (user_id, posting_id, comment) values (1, 35, '끝이 보일락 말락');
insert into comment (user_id, posting_id, comment) values (3, 24, '후후');
insert into comment (user_id, posting_id, comment) values (7, 23, 'vscode free');
insert into comment (user_id, posting_id, comment) values (5, 44, '도비는 자유에요');
insert into comment (user_id, posting_id, comment) values (9, 37, '마지막 덧글입니다.');


-- migrate:down

